apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clusterissuer-astorx-com
  namespace: tools
spec:
  issuerRef:
    name: clusterissuer-astorx-com
    kind: ClusterIssuer
  secretName: clusterissuer-astorx-com
  commonName: "*.astorx.com"
  dnsNames:
  - "*.astorx.com"
  - "astorx.com"
