apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clusterissuer-zvonimirbedi-com
  namespace: tools
spec:
  issuerRef:
    name: clusterissuer-zvonimirbedi-com
    kind: ClusterIssuer
  secretName: clusterissuer-zvonimirbedi-com
  commonName: "*.zvonimirbedi.com"
  dnsNames:
  - "*.zvonimirbedi.com"
